[package]
name = "ic_vector_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
schemars = "0.8.12"
serde = "1.0.165"
thiserror = "1.0.40"
rayon = "1.7.0"
candid = "0.8"
ic-cdk = "0.7"


